baseURL = 'https://kindredsm.github.io/Cerebration/'
languageCode = 'en-us'
title = 'Cerebration'
theme = "ananke"
resourceDir = "../resources"

[params]
  text_color = "black"
  author = "Kindred Salway"
  favicon = ""
  site_logo = ""
  description = "Philosophy in the age of tech."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 10

[[params.ananke_socials]]
name = "github"
url = "https://github.com/kindredsm"